### ISSUE TITLE
TouchScreen Support

### ISSUE THREAD

**Issue by SiddharthaBhattacharjee** [SiddharthaBhattacharjee/TimePassGames#12]
## Snake Game is Not supported on touch screen devices
The game Feed The Snake is not supported for screen touch devices, It needs to be adapted for mobile and other touch screen devices by adding transparent buttons or some other form of control. As of now, the game relies on keyboard for user input.

**Comment by burned42** [comment]
This didn't sound too complicated to I gave it a try and submitted a PR: https://github.com/SiddharthaBhattacharjee/TimePassGames/pull/18

It was also a good opportunity to learn a bit more about grid and flexboxes, too, on the way :smile:
